import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=fs.readFileSync(new URL('../supabase/migrations/20260828_pyeongjae_archive.sql',import.meta.url),'utf8');
const sheet=fs.readFileSync(new URL('../supabase/migrations/20260828_pyeongjae_sheet_model.sql',import.meta.url),'utf8');
const face=fs.readFileSync(new URL('../supabase/migrations/20260828_pyeongjae_face_model.sql',import.meta.url),'utf8');
const archive=fs.readFileSync(new URL('../pyeongjae/index.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../pyeongjae/pyeongjae.css',import.meta.url),'utf8');
const detail=fs.readFileSync(new URL('../api/pyeongjae.js',import.meta.url),'utf8');
const admin=fs.readFileSync(new URL('../admin/index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../admin/admin.js',import.meta.url),'utf8');
const sitemap=fs.readFileSync(new URL('../api/sitemap.js',import.meta.url),'utf8');
const guides=fs.readFileSync(new URL('../guides/index.html',import.meta.url),'utf8');
for(const text of ['create table if not exists public.pyeongjae_entries','pages jsonb','reference_links jsonb','increment_pyeongjae_view'])assert.ok(base.includes(text),text);
for(const text of ['sheet_no integer','admin_note text','pyeongjae_book_sheet_unique','alter column volume_no drop not null'])assert.ok(sheet.includes(text),text);
for(const text of ["side in ('front','back')",'pyeongjae_book_sheet_side_unique','book_no,sheet_no,side','卷之一'])assert.ok(face.includes(text),text);
for(const migration of [sheet,face])assert.doesNotMatch(migration,/drop table|truncate/i);
for(const text of ['PAGE_SIZE=15','data-book="1"','data-book="2"','data-book="3"','data-genre="편지"','faceOrder','face-row','face-meta'])assert.ok(archive.includes(text),text);
for(const text of ['id="pj-book"','id="pj-sheet"','id="pj-side"','id="pj-volume"','id="pj-genre"','id="pj-free-title"'])assert.ok(admin.includes(text),text);
for(const text of ['원문과 음독','현대어 직역','현대어 의역','참고'])assert.ok(js.includes(text),text);
for(const text of ['pjBookSheetCompare','side,genre:','pjAutoTitle','pj-free-title','pjDuplicateWarning','원문과 음독'])assert.ok(js.includes(text),text);
for(const text of ['ScholarlyArticle','canonical','status=eq.published','현대어 직역',"section('원문과 음독'",'faceLabel'])assert.ok(detail.includes(text),text);
assert.doesNotMatch(detail,/>1\. 원문과 음독</);
assert.doesNotMatch(detail,/>2\. 현대어 직역</);
assert.ok(sitemap.includes('pyeongjae-entry')&&sitemap.includes('status=eq.published'));
assert.ok(guides.includes("order('book_no').order('sheet_no')")&&guides.includes("kicker:''"));
for(const text of ['.face-row','.face-title','.face-meta','@media(max-width:600px)','font-size:18px','padding:18px 19px'])assert.ok(css.includes(text),text);
new Function(js);
for(const page of [archive,guides])for(const match of page.matchAll(/<script(?![^>]*application\/ld\+json)[^>]*>([\s\S]*?)<\/script>/g))if(match[1].trim())new Function(match[1]);
const sample=[{book_no:1,sheet_no:2,side:'back'},{book_no:1,sheet_no:1,side:'back'},{book_no:1,sheet_no:1,side:'front'},{book_no:1,sheet_no:2,side:'front'}];
const order=v=>v.side==='back'?2:1;
sample.sort((a,b)=>(a.book_no-b.book_no)||(a.sheet_no-b.sheet_no)||(order(a)-order(b)));
assert.deepEqual(sample.map(x=>x.sheet_no+':'+x.side),['1:front','1:back','2:front','2:back']);
console.log('pyeongjae face archive: PASS');
