import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=fs.readFileSync(new URL('../supabase/migrations/20260828_pyeongjae_archive.sql',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../supabase/migrations/20260828_pyeongjae_sheet_model.sql',import.meta.url),'utf8');
const archive=fs.readFileSync(new URL('../pyeongjae/index.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../pyeongjae/pyeongjae.css',import.meta.url),'utf8');
const detail=fs.readFileSync(new URL('../api/pyeongjae.js',import.meta.url),'utf8');
const admin=fs.readFileSync(new URL('../admin/index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../admin/admin.js',import.meta.url),'utf8');
const sitemap=fs.readFileSync(new URL('../api/sitemap.js',import.meta.url),'utf8');
const guides=fs.readFileSync(new URL('../guides/index.html',import.meta.url),'utf8');
for(const text of ['create table if not exists public.pyeongjae_entries','pages jsonb','reference_links jsonb','increment_pyeongjae_view'])assert.ok(base.includes(text));
for(const text of ['sheet_no integer','admin_note text','pyeongjae_book_sheet_unique','alter column volume_no drop not null'])assert.ok(migration.includes(text));
assert.doesNotMatch(migration,/drop table|truncate/i);
for(const text of ['PAGE_SIZE=15','data-book="1"','data-book="2"','data-book="3"','복합·경계','compareBookSheet','page-state'])assert.ok(archive.includes(text),text);
for(const text of ['id="pj-sheet"','id="pj-book-filter"','id="pj-genre-filter"','id="pj-review-filter"','한 장의 양면'])assert.ok(admin.includes(text),text);
for(const text of ['pjBookSheetCompare','sheet_no:sheet','제${book}책 제${sheet}장은 이미 등록되어 있습니다.','pjNormalizedPages','data-pj-action="toggle"'])assert.ok(js.includes(text),text);
for(const text of ['ScholarlyArticle','canonical','status=eq.published','article:tag','제${row.sheet_no}장','이전 자료','다음 자료'])assert.ok(detail.includes(text),text);
assert.ok(sitemap.includes('pyeongjae-entry')&&sitemap.includes('status=eq.published'));
assert.ok(guides.includes("order('book_no').order('sheet_no')")&&guides.includes('제${r.sheet_no}장'));
assert.match(css,/\.sheet-row/);
new Function(js);
[archive,guides].forEach(page=>[...page.matchAll(/<script(?![^>]*application\/ld\+json)[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).filter(x=>x.trim()).forEach(x=>new Function(x)));
const sample=[{book_no:3,sheet_no:1},{book_no:3,sheet_no:59},{book_no:3,sheet_no:41},{book_no:3,sheet_no:2}];
sample.sort((a,b)=>(a.book_no-b.book_no)||(a.sheet_no-b.sheet_no));assert.deepEqual(sample.map(x=>x.sheet_no),[1,2,41,59]);
assert.equal(new Set(sample.map(x=>`${x.book_no}:${x.sheet_no}`)).size,4);
console.log('pyeongjae sheet archive: PASS');
