import assert from 'node:assert/strict';
import fs from 'node:fs';
const migration=fs.readFileSync(new URL('../supabase/migrations/20260828_pyeongjae_archive.sql',import.meta.url),'utf8');
const archive=fs.readFileSync(new URL('../pyeongjae/index.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../pyeongjae/pyeongjae.css',import.meta.url),'utf8');
const detail=fs.readFileSync(new URL('../api/pyeongjae.js',import.meta.url),'utf8');
const admin=fs.readFileSync(new URL('../admin/index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../admin/admin.js',import.meta.url),'utf8');
const sitemap=fs.readFileSync(new URL('../api/sitemap.js',import.meta.url),'utf8');
const home=fs.readFileSync(new URL('../customer/index.html',import.meta.url),'utf8');
const guides=fs.readFileSync(new URL('../guides/index.html',import.meta.url),'utf8');
const vercel=JSON.parse(fs.readFileSync(new URL('../vercel.json',import.meta.url),'utf8'));
for(const text of ['create table if not exists public.pyeongjae_entries','pages jsonb','reference_links jsonb','status=\'published\' or public.is_admin','increment_pyeongjae_view','pyeongjae_view_events'])assert.ok(migration.includes(text));
assert.doesNotMatch(migration,/drop table|truncate/i);assert.doesNotMatch(migration,/^\s*references\s+jsonb/im);
for(const text of ['『평재문집』','소개 더 보기','전체 권차','원책 순서','pyeongjae_entries'])assert.ok(archive.includes(text));
for(const text of ['data-view="pyeongjae"','id="pyeongjae-form"','id="pj-paste"','id="pj-page-editor"'])assert.ok(admin.includes(text));
for(const text of ['loadPyeongjae','pjParsePaste','data-pj-action="restore"','data-pj-action="delete"','최대 다섯 쪽'])assert.ok(js.includes(text));
for(const text of ['ScholarlyArticle','canonical','status=eq.published','article:tag','원문과 음독','현대어 직역','현대어 의역','정정·제보하기','p_viewer'])assert.ok(detail.includes(text));
assert.ok(sitemap.includes('pyeongjae-entry')&&sitemap.includes("status=eq.published"));
assert.ok(home.includes("name==='평재문집'"));
assert.ok(guides.includes('data-scope="pyeongjae"')&&guides.includes('scope=b.dataset.scope'));
assert.ok(vercel.rewrites.some(x=>x.source==='/pyeongjae'));
assert.ok(vercel.rewrites.some(x=>x.source==='/pyeongjae-entry'));
assert.match(css,/\.entry-row\{display:grid/);assert.match(css,/@media\(max-width:520px\)/);
new Function(js);
[archive,guides].forEach(page=>[...page.matchAll(/<script(?![^>]*application\/ld\+json)[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).filter(x=>x.trim()).forEach(x=>new Function(x)));
console.log('pyeongjae archive: PASS');
