import assert from 'node:assert/strict';
import handler from '../api/pyeongjae.js';
const id='11111111-1111-4111-8111-111111111111';
const row={id,book_no:1,sheet_no:1,volume_no:1,start_page:1,end_page:1,side:'front',genre:'시',work_title:'',title:'평재문집 제1책 제1장 앞면',summary:'',people:[],places:[],tags:['평재문집'],review_status:'초벌 정리',status:'published',view_count:0,created_at:'2026-08-28T00:00:00Z',updated_at:'2026-08-28T01:00:00Z',pages:[{page:1,side:'front',genre:'시',original_reading:'漢文\n<script>alert(1)</script>',literal_translation:'직역',interpretive_translation:'',notes:'참고'}],reference_links:[]};
const originalFetch=global.fetch;
global.fetch=async url=>({ok:true,status:200,json:async()=>String(url).includes('select=id%2Cbook_no')?[{id,book_no:1,sheet_no:1,side:'front',status:'published'}]:[row]});
let body='',status=0,headers={};
const response={setHeader:(k,v)=>headers[k]=v,status:n=>{status=n;return response},send:v=>{body=v;return response}};
await handler({query:{id}},response);
global.fetch=originalFetch;
assert.equal(status,200);
assert.equal(headers['Content-Type'],'text/html; charset=utf-8');
for(const text of ['평재문집 제1책 제1장 앞면','권1','시','조회 0','원문과 음독','漢文','현대어 직역','직역','참고','canonical','ScholarlyArticle','reader-nav-primary','제1책 · 제1장 · 앞면 · 시','reader-nav-20260828-1'])assert.ok(body.includes(text),text);
assert.ok(body.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));
assert.ok(!body.includes('<script>alert(1)</script>'));
assert.ok(!body.includes('현대어 의역'));
for(const numbered of ['1. 원문과 음독','2. 현대어 직역','3. 현대어 의역','4. 참고'])assert.ok(!body.includes(numbered),numbered);
console.log('pyeongjae face server render: PASS');
