(()=>{
  'use strict';
  const synth=window.speechSynthesis,Utterance=window.SpeechSynthesisUtterance;
  const titleSelector='.article-head h1,.document-head h1,.reader-head h1,.video-page h1';
  const bodySelector='.article-body .reader-text-content,.document-body.reader-text-content,.pyeongjae-guide-body.reader-text-content,.pyeongjae-text.reader-text-content,.video-copy';
  let mounted=false,segments=[],index=0,rate=1,run=0,currentNode=null,voices=[],selectedVoice=null,observer=null,retryTimer=0,retryCount=0,stabilityTimer=0,bodyMissingLogged=false;
  const clean=value=>String(value||'').replace(/https?:\/\/\S+/gi,' ').replace(/\s+/g,' ').trim();
  function visible(node){return node.getClientRects().length>0&&!node.closest('[hidden],[aria-hidden="true"]')}
  function spokenText(node){const copy=node.cloneNode(true);copy.querySelectorAll('script,style,noscript,img,svg,video,audio,iframe,.sr-only,[hidden],[aria-hidden="true"]').forEach(item=>item.remove());copy.querySelectorAll('a').forEach(link=>{const text=clean(link.textContent);if(/^https?:\/\//i.test(text)||/^[\[\]()†‡*\d\s.\-]+$/.test(text))link.remove()});return clean(copy.textContent)}
  function split(text,node){if(text.length<=240)return[{text,node}];const sentences=text.match(/[^.!?。！？]+[.!?。！？]?/g)||[text],result=[];let part='';for(const sentence of sentences){if(part&&`${part} ${sentence}`.length>240){result.push({text:part.trim(),node});part=''}part+=`${part?' ':''}${sentence}`}if(part.trim())result.push({text:part.trim(),node});return result}
  function collect(){const result=[],title=document.querySelector(titleSelector);if(title&&visible(title)){const text=spokenText(title);if(text)result.push(...split(text,title))}document.querySelectorAll(bodySelector).forEach(root=>{if(!visible(root))return;const nodes=[...root.querySelectorAll('h1,h2,h3,h4,h5,h6,p,li,blockquote,th,td,.text-part>div')].filter(node=>visible(node)&&!node.querySelector('h1,h2,h3,h4,h5,h6,p,li,blockquote,th,td,.text-part>div'));if(!nodes.length){const text=spokenText(root);if(text)result.push(...split(text,root));return}nodes.forEach(node=>{const text=spokenText(node);if(text&&!/^[\[\]()†‡*\d\s.\-]+$/.test(text))result.push(...split(text,node))})});return result}
  function refreshVoices(){voices=synth?.getVoices?.()||[];const ko=voices.filter(item=>/^ko(?:-|$)/i.test(item.lang));selectedVoice=ko.sort((a,b)=>Number(/Google|Microsoft|Siri|Samsung|Natural|Online/i.test(b.name))-Number(/Google|Microsoft|Siri|Samsung|Natural|Online/i.test(a.name)))[0]||null;return voices}
  function voice(){if(!voices.length)refreshVoices();return selectedVoice}
  function clearHighlight(){if(currentNode)currentNode.classList.remove('reader-speaking');currentNode=null}
  function setHighlight(node){if(currentNode===node)return;clearHighlight();currentNode=node;node?.classList.add('reader-speaking');node?.scrollIntoView?.({block:'center',behavior:'smooth'})}
  let controls,status,start,pause,resume,restart,stopButton,speed;
  function state(mode,message=''){if(!controls)return;const playing=mode==='playing',isPaused=mode==='paused';start.disabled=playing||isPaused;pause.disabled=!playing;resume.disabled=!isPaused;restart.disabled=!(playing||isPaused||mode==='finished'||mode==='stopped');stopButton.disabled=!(playing||isPaused);const labels={ready:'읽을 준비가 되었습니다.',playing:'본문을 읽고 있습니다.',paused:'읽기를 일시정지했습니다.',stopped:'읽기를 정지했습니다.',finished:'본문 읽기가 끝났습니다.',empty:'읽을 본문이 없습니다.',error:'기기의 음성 읽기를 시작하지 못했습니다.',unsupported:'이 브라우저에서는 읽어주기를 지원하지 않습니다.'};status.textContent=message||labels[mode]||''}
  function stop(update=true){run+=1;synth?.cancel();clearHighlight();if(update)state('stopped')}
  function speakNext(token){if(token!==run)return;if(index>=segments.length){clearHighlight();state('finished');return}const segment=segments[index],utterance=new Utterance(segment.text),selected=voice();utterance.lang='ko-KR';utterance.rate=rate;if(selected)utterance.voice=selected;utterance.onstart=()=>{if(token===run){setHighlight(segment.node);state('playing')}};utterance.onend=()=>{if(token===run){index+=1;speakNext(token)}};utterance.onerror=event=>{if(token!==run||event.error==='canceled'||event.error==='interrupted')return;clearHighlight();state('error')};synth.speak(utterance)}
  function begin(fromStart=true){if(!synth||!Utterance){console.warn('[읽어주기] Web Speech API 미지원');return state('unsupported')}if(!refreshVoices().length){console.info('[읽어주기] 음성 목록 준비 중');return state('voices-loading','한국어 음성을 준비하고 있습니다. 잠시 후 다시 눌러 주세요.')}stop(false);segments=collect();if(!segments.length)return state('empty');if(fromStart)index=0;const selected=voice(),token=run;state('playing',selected?'본문을 읽고 있습니다.':'한국어 음성을 찾지 못해 기기의 기본 음성을 사용합니다.');speakNext(token)}
  function bindExisting(existing){controls=existing;status=controls.querySelector('.read-aloud-status');start=controls.querySelector('.read-aloud-start');pause=controls.querySelector('.read-aloud-pause');resume=controls.querySelector('.read-aloud-resume');restart=controls.querySelector('.read-aloud-restart');stopButton=controls.querySelector('.read-aloud-stop');speed=controls.querySelector('select');mounted=true}
  function mount(){const existing=document.querySelector('.read-aloud-controls');if(existing){if(!mounted||controls!==existing)bindExisting(existing);return true}mounted=false;controls=null;const anchor=document.querySelector('.reader-font-controls')||document.querySelector('.article-head,.document-head,.reader-head,.video-page .video-meta'),body=document.querySelector(bodySelector);if(!anchor||!body){if(!bodyMissingLogged){console.info('[읽어주기] 본문 미발견');bodyMissingLogged=true}return false}bodyMissingLogged=false;controls=document.createElement('div');controls.className='read-aloud-controls';if(anchor.matches('.article-head,.reader-font-controls.wrap'))controls.classList.add('wrap');controls.setAttribute('role','group');controls.setAttribute('aria-label','본문 읽어주기 조절');controls.innerHTML='<button class="read-aloud-start" type="button" aria-label="본문 읽어주기 시작">🔊 읽어주기</button><button class="read-aloud-pause" type="button" aria-label="본문 읽기 일시정지">일시정지</button><button class="read-aloud-resume" type="button" aria-label="본문 계속 듣기">계속 듣기</button><button class="read-aloud-restart" type="button" aria-label="본문 처음부터 다시 듣기">처음부터</button><button class="read-aloud-stop" type="button" aria-label="본문 읽기 정지">정지</button><label class="read-aloud-speed-label">속도 <select aria-label="읽어주기 속도"><option value="0.8">0.8배</option><option value="1" selected>1.0배</option><option value="1.2">1.2배</option><option value="1.5">1.5배</option></select></label><p class="read-aloud-status" role="status" aria-live="polite"></p>';anchor.insertAdjacentElement('afterend',controls);bindExisting(controls);start.addEventListener('click',()=>begin(true));pause.addEventListener('click',()=>{if(synth?.speaking&&!synth.paused){synth.pause();state('paused')}});resume.addEventListener('click',()=>{if(synth?.paused){synth.resume();state('playing')}});restart.addEventListener('click',()=>begin(true));stopButton.addEventListener('click',()=>stop());speed.addEventListener('change',()=>{rate=Number(speed.value)||1;if(synth?.speaking||synth?.paused)begin(false)});if(!synth||!Utterance){console.warn('[읽어주기] Web Speech API 미지원');state('unsupported')}else{refreshVoices();state('ready')}return true}
  function finishWatching(){if(retryTimer){clearTimeout(retryTimer);retryTimer=0}retryCount=0;if(stabilityTimer)clearTimeout(stabilityTimer);stabilityTimer=setTimeout(()=>{if(observer){observer.disconnect();observer=null}stabilityTimer=0},1500)}
  function ensureObserver(){if(observer)return;observer=new MutationObserver(()=>{if(mount())finishWatching()});observer.observe(document.documentElement,{childList:true,subtree:true})}
  function initialize(){ensureObserver();if(mount()){finishWatching();return true}if(!retryTimer&&retryCount<20){retryTimer=setTimeout(()=>{retryTimer=0;retryCount+=1;initialize()},250)}return false}
  window.LanguageBrainReadAloud={initialize,refreshVoices};
  if(synth?.addEventListener)synth.addEventListener('voiceschanged',()=>{refreshVoices();if(controls&&status?.textContent.includes('준비하고 있습니다'))state('ready')});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize,{once:true});else initialize();
  window.addEventListener('pageshow',()=>{initialize();setTimeout(initialize,300)});
  window.addEventListener('pagehide',()=>stop(false));window.addEventListener('beforeunload',()=>stop(false));
})();
