-- 언어와 문해 연구실 관리자 작업실 v3
-- 기존 posts/profiles/inquiries 데이터는 유지하고 기능에 필요한 열과 테이블만 추가합니다.

begin;

alter table public.posts add column if not exists content_html text not null default '';
alter table public.posts add column if not exists subtitle text not null default '';
alter table public.posts add column if not exists tags text[] not null default '{}';
alter table public.posts add column if not exists image_alt text not null default '';
alter table public.posts add column if not exists working_content jsonb not null default '{}'::jsonb;
alter table public.posts add column if not exists deleted_at timestamptz;

alter table public.posts drop constraint if exists posts_type_check;
alter table public.posts add constraint posts_type_check
  check (type in ('paper', 'works', 'news', 'notice', 'other'));

alter table public.posts drop constraint if exists posts_status_check;
alter table public.posts add constraint posts_status_check
  check (status in ('draft', 'published', 'trashed'));

update public.posts
set working_content = jsonb_build_object(
  'type', type,
  'category', category,
  'title', title,
  'subtitle', subtitle,
  'excerpt', excerpt,
  'content_html', content_html,
  'academic_info', academic_info,
  'source', source,
  'link_url', link_url,
  'image_url', image_url,
  'image_alt', image_alt,
  'tags', tags,
  'published_at', published_at
)
where working_content = '{}'::jsonb;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  description text not null default '',
  image_url text not null default '',
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  bucket text not null default 'post-images',
  path text not null unique,
  file_name text not null,
  public_url text not null,
  alt_text text not null default '',
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 8388608),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.post_views (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  visitor_hash text not null check (char_length(visitor_hash) between 8 and 64),
  viewed_on date not null default current_date,
  created_at timestamptz not null default now(),
  unique(post_id, visitor_hash, viewed_on)
);

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at before update on public.categories
for each row execute function public.set_updated_at();

insert into public.categories (name, slug, description, sort_order) values
('읽기와 뇌', 'reading-brain', '읽기 과정과 뇌의 인지·신경 기제를 탐구합니다.', 10),
('쓰기와 뇌', 'writing-brain', '글쓰기와 사고, 기억의 관계를 살펴봅니다.', 20),
('듣기와 뇌', 'listening-brain', '언어 이해와 소리 처리 과정을 탐구합니다.', 30),
('말하기와 뇌', 'speaking-brain', '말소리와 표현, 의사소통의 기제를 살펴봅니다.', 40),
('문해학습과 뇌', 'literacy-learning', '문해 발달과 학습이 뇌에 미치는 영향을 다룹니다.', 50),
('디지털·AI와 인지', 'digital-ai-cognition', '디지털 환경과 AI가 인간의 사고에 미치는 영향을 탐색합니다.', 60),
('언어와 인간', 'language-human', '언어가 인간의 사고·사회·문화와 연결되는 방식을 살펴봅니다.', 70)
on conflict (name) do nothing;

alter table public.categories enable row level security;
alter table public.media_assets enable row level security;
alter table public.post_views enable row level security;

drop policy if exists "categories_public_read" on public.categories;
create policy "categories_public_read" on public.categories
for select to anon, authenticated using (is_visible or public.is_admin());

drop policy if exists "categories_admin_insert" on public.categories;
create policy "categories_admin_insert" on public.categories
for insert to authenticated with check (public.is_admin());

drop policy if exists "categories_admin_update" on public.categories;
create policy "categories_admin_update" on public.categories
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "categories_admin_delete" on public.categories;
create policy "categories_admin_delete" on public.categories
for delete to authenticated using (public.is_admin());

drop policy if exists "media_admin_read" on public.media_assets;
create policy "media_admin_read" on public.media_assets
for select to authenticated using (public.is_admin());

drop policy if exists "media_admin_insert" on public.media_assets;
create policy "media_admin_insert" on public.media_assets
for insert to authenticated with check (public.is_admin() and created_by = auth.uid());

drop policy if exists "media_admin_update" on public.media_assets;
create policy "media_admin_update" on public.media_assets
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "views_admin_read" on public.post_views;
create policy "views_admin_read" on public.post_views
for select to authenticated using (public.is_admin());

create or replace function public.record_post_view(target_post uuid, visitor text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.posts
    where id = target_post and status = 'published'
  ) then
    return false;
  end if;

  insert into public.post_views(post_id, visitor_hash)
  values (target_post, left(visitor, 64))
  on conflict (post_id, visitor_hash, viewed_on) do nothing;
  return true;
end;
$$;

revoke all on function public.record_post_view(uuid, text) from public;
grant execute on function public.record_post_view(uuid, text) to anon, authenticated;

grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant select, insert, update on public.media_assets to authenticated;
grant select on public.post_views to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'post-images',
  'post-images',
  true,
  8388608,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;
