import { SITE_URL, escapeHtml, supabaseRows } from './_seo.js';
const clean=v=>String(v||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim();
const safeUrl=v=>{try{const u=new URL(String(v||''));return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
const isGuide=row=>row?.entry_kind==='guide';
function safeRichHtml(value){
 const allowed=new Set(['p','br','div','strong','b','u','em','i','span','a','ol','ul','li','table','thead','tbody','tr','th','td','img','h2','h3','blockquote']);
 return String(value||'').replace(/<(script|style|iframe|object|embed)[^>]*>[\s\S]*?<\/\1\s*>/gi,'').replace(/<[^>]+>/g,tag=>{const match=tag.match(/^<\s*(\/?)\s*([a-z0-9]+)/i);if(!match)return'';const closing=Boolean(match[1]),name=match[2].toLowerCase();if(!allowed.has(name))return'';if(closing)return`</${name}>`;if(name==='br')return'<br>';if(name==='a'){const href=safeUrl(tag.match(/\bhref\s*=\s*["']([^"']+)["']/i)?.[1]);return href?`<a href="${escapeHtml(href)}" target="_blank" rel="noopener noreferrer">`:''}if(name==='img'){const src=safeUrl(tag.match(/\bsrc\s*=\s*["']([^"']+)["']/i)?.[1]);if(!src)return'';const alt=tag.match(/\balt\s*=\s*["']([^"']*)["']/i)?.[1]||'';return`<img src="${escapeHtml(src)}" alt="${escapeHtml(alt)}">`}if(name==='span'){const color=tag.match(/\bstyle\s*=\s*["'][^"']*color\s*:\s*(#[0-9a-f]{3,8}|rgb\([^)]*\)|[a-z]+)[^"']*["']/i)?.[1];return color?`<span style="color:${escapeHtml(color)}">`:'<span>'}if(name==='th'||name==='td'){const colspan=tag.match(/\bcolspan\s*=\s*["']?([1-9][0-9]?)/i)?.[1],rowspan=tag.match(/\browspan\s*=\s*["']?([1-9][0-9]?)/i)?.[1];return`<${name}${colspan?` colspan="${colspan}"`:''}${rowspan?` rowspan="${rowspan}"`:''}>`}return`<${name}>`});
}
const section=(title,text,cls='')=>text?`<section class="text-part ${cls}"><h3>${escapeHtml(title)}</h3><div>${escapeHtml(text)}</div></section>`:'';
const faceLabel=side=>side==='back'?'뒷면':'앞면';
const priorityRank=row=>{const title=String(row?.title||'').trimStart();if(isGuide(row)||title.startsWith('○')||title.startsWith('#'))return title.startsWith('○')?0:title.startsWith('#')?1:2;return 3};
const isPriority=row=>priorityRank(row)<3;
const createdTime=row=>Date.parse(row?.created_at||row?.published_at||row?.updated_at||'')||0;
const compareEntries=(a,b)=>priorityRank(a)-priorityRank(b)||(isPriority(a)&&isPriority(b)?createdTime(a)-createdTime(b):0)||(Number(a.book_no||0)-Number(b.book_no||0))||(Number(a.sheet_no||0)-Number(b.sheet_no||0))||((a.side==='back'?1:0)-(b.side==='back'?1:0));
function pageMarkup(page,row){return `<section class="page-block"><p class="page-label">제${row.book_no}책 · 제${row.sheet_no}장 · ${faceLabel(row.side)} · ${escapeHtml(row.genre)}</p>${page.marker?`<p class="review-note">${escapeHtml(page.marker)}</p>`:''}<div class="pyeongjae-text reader-text-content" style="--reader-body-size:18px;--reader-subhead-size:17px">${section('원문과 음독',page.original_reading,'original')}${section('현대어 직역',page.literal_translation)}${section('현대어 의역',page.interpretive_translation)}${section('참고',page.notes)}</div></section>`}
export default async function handler(request,response){
 const id=String(Array.isArray(request.query?.id)?request.query.id[0]:request.query?.id||'');response.setHeader('Content-Type','text/html; charset=utf-8');
 if(!/^[0-9a-f-]{36}$/i.test(id)){response.setHeader('X-Robots-Tag','noindex,nofollow');return response.status(400).send('잘못된 주소입니다.')}
 try{
  const [row]=await supabaseRows('pyeongjae_entries',`select=*&id=eq.${encodeURIComponent(id)}&status=eq.published&limit=1`);
  if(!row){response.setHeader('X-Robots-Tag','noindex,nofollow');return response.status(404).send('<!doctype html><meta charset="utf-8"><title>자료 없음</title><p>공개되지 않았거나 존재하지 않는 자료입니다.</p>')}
  const all=(await supabaseRows('pyeongjae_entries','select=id,entry_kind,book_no,sheet_no,side,status,title,created_at,published_at,updated_at&status=eq.published')).sort(compareEntries);
  const pos=all.findIndex(x=>x.id===row.id),prev=all[pos-1],next=all[pos+1],canonical=`${SITE_URL}/pyeongjae-entry?id=${encodeURIComponent(row.id)}`,displayTitle=row.title,guide=isGuide(row);
  const guidePlain=clean(String(row.guide_body||'').replace(/<[^>]+>/g,' ')),description=clean(row.summary||(guide?guidePlain:`${row.title} — 원문·음독·직역·의역·참고.`)).slice(0,170),tags=[...(row.people||[]),...(row.places||[]),...(row.tags||[])],keywords=guide?['평재문집','안내 글',...tags]:['평재문집',`제${row.book_no}책`,`제${row.sheet_no}장`,faceLabel(row.side),row.genre,...(row.volume_no?[`권${row.volume_no}`]:[]),...tags];
  const allPages=Array.isArray(row.pages)?row.pages:[],matched=allPages.filter(p=>p.side===row.side),pages=matched.length?matched:allPages.slice(0,1);
  const schema={'@context':'https://schema.org','@type':guide?'Article':'ScholarlyArticle',headline:displayTitle,description,url:canonical,mainEntityOfPage:canonical,inLanguage:guide?'ko':['ko','zh-Hant'],datePublished:row.published_at||row.created_at,dateModified:row.updated_at,keywords,author:{'@type':'Person',name:guide?'권우진':'권태직'},publisher:{'@type':'Organization',name:'삶과 언어 | 권우진 연구실'}};
  const locationLabel=guide?'『평재문집』 · 안내 글':[`제${row.book_no}책`,`제${row.sheet_no}장`,faceLabel(row.side),row.genre].filter(Boolean).map(escapeHtml).join(' · ');
  const nav=primary=>primary?`<nav class="reader-nav reader-nav-primary" aria-label="자료 탐색">${prev?`<a class="reader-prev" href="/pyeongjae-entry?id=${prev.id}">← 이전 자료</a>`:'<span class="reader-prev"></span>'}<a class="reader-position" href="/pyeongjae" aria-label="평재문집 전체 목록으로 이동">${locationLabel}</a>${next?`<a class="reader-next" href="/pyeongjae-entry?id=${next.id}">다음 자료 →</a>`:'<span class="reader-next"></span>'}</nav>`:`<nav class="reader-nav">${prev?`<a href="/pyeongjae-entry?id=${prev.id}">← 이전 자료</a>`:'<span></span>'}<a href="/pyeongjae">전체 목록</a>${next?`<a href="/pyeongjae-entry?id=${next.id}">다음 자료 →</a>`:'<span></span>'}</nav>`;
  const refs=(Array.isArray(row.reference_links)?row.reference_links:[]).map(ref=>{const url=safeUrl(ref?.url);return url?`<li><a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(ref.label||url)}</a></li>`:''}).join('');
  const review=guide||row.review_status==='검토 완료'?'':`<p class="review-note">이 자료는 원문 판독과 번역을 계속 검토하고 있습니다. 불확실한 글자와 인명·지명은 확인되는 대로 보완합니다.</p>`;
  const meta=guide?`안내 글 · 조회 ${Number(row.view_count||0).toLocaleString()}`:`${row.volume_no?`권${row.volume_no} · `:''}${escapeHtml(row.genre)} · 조회 ${Number(row.view_count||0).toLocaleString()}`;
  const mainBody=guide?`<article class="pyeongjae-guide-body reader-text-content" style="--reader-body-size:18px;--reader-subhead-size:22px">${safeRichHtml(row.guide_body)}</article>`:pages.map(p=>pageMarkup(p,row)).join('');
  const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(displayTitle)} | ${guide?'삶과 언어':'『평재문집』'}</title><meta name="description" content="${escapeHtml(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${escapeHtml(canonical)}"><meta property="og:type" content="article"><meta property="og:title" content="${escapeHtml(displayTitle)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${escapeHtml(canonical)}">${keywords.map(k=>`<meta property="article:tag" content="${escapeHtml(k)}">`).join('')}<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><link rel="stylesheet" href="/pyeongjae/pyeongjae.css?v=guide-20260913-1"><link rel="stylesheet" href="/customer/reader-text-size.css?v=20260909-3"></head><body><header class="site-header"><a href="/">삶과 언어</a><nav><a href="/pyeongjae">평재문집 목록</a><a href="/">홈</a></nav></header><main class="reader"><header class="reader-head"><p class="reader-kicker">${meta}</p><h1>${escapeHtml(displayTitle)}</h1><div class="reader-meta"><span>최근 수정 ${new Date(row.updated_at).toLocaleDateString('ko-KR')}</span></div><div class="reader-tags">${tags.map(t=>`<a href="/pyeongjae?q=${encodeURIComponent(t)}">#${escapeHtml(t)}</a>`).join('')}</div>${review}</header>${nav(true)}${mainBody}${refs?`<section class="text-part"><h3>관련 문헌과 링크</h3><ul>${refs}</ul></section>`:''}<div class="correction"><a href="/?inquiry=question#about">정정·제보하기</a><button class="share" type="button">공유하기</button></div><p class="reader-bottom-position">${locationLabel}</p>${nav(false)}</main><script src="/api/config"></script><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js"></script><script>const c=window.LANGUAGE_BRAIN_CONFIG;if(c?.supabaseUrl&&c?.supabasePublishableKey){const d=supabase.createClient(c.supabaseUrl,c.supabasePublishableKey);let v=localStorage.getItem('pj-viewer');if(!v){v=crypto.randomUUID();localStorage.setItem('pj-viewer',v)}d.rpc('increment_pyeongjae_view',{p_entry_id:'${row.id}',p_viewer:v})}document.querySelector('.share').onclick=async()=>{const x={title:document.title,url:location.href};if(navigator.share)try{await navigator.share(x)}catch(e){}else try{await navigator.clipboard.writeText(location.href);alert('링크가 복사되었습니다')}catch(e){prompt('주소를 복사하세요',location.href)}}</script><script src="/customer/reader-text-size.js?v=20260909-2"></script></body></html>`;
  response.setHeader('Cache-Control','public,max-age=0,s-maxage=300,stale-while-revalidate=3600');return response.status(200).send(html)
 }catch(e){response.setHeader('X-Robots-Tag','noindex,nofollow');return response.status(503).send('<!doctype html><meta charset="utf-8"><title>자료를 불러올 수 없습니다</title><p>잠시 후 다시 시도해 주세요.</p>')}
}
