import { SITE_URL, escapeHtml, supabaseRows } from './_seo.js';
const clean=v=>String(v||'').replace(/[\u0000-\u001f\u007f]/g,' ').trim();
const safeUrl=v=>{try{const u=new URL(String(v||''));return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
const section=(title,text,cls='')=>text?`<section class="text-part ${cls}"><h3>${escapeHtml(title)}</h3><div>${escapeHtml(text)}</div></section>`:'';
const faceLabel=side=>side==='back'?'뒷면':'앞면';
function pageMarkup(page,row){return `<section class="page-block"><p class="page-label">제${row.book_no}책 · 제${row.sheet_no}장 · ${faceLabel(row.side)} · ${escapeHtml(row.genre)}</p>${page.marker?`<p class="review-note">${escapeHtml(page.marker)}</p>`:''}${section('원문과 음독',page.original_reading,'original')}${section('현대어 직역',page.literal_translation)}${section('현대어 의역',page.interpretive_translation)}${section('참고',page.notes)}</section>`}
export default async function handler(request,response){
 const id=String(Array.isArray(request.query?.id)?request.query.id[0]:request.query?.id||'');response.setHeader('Content-Type','text/html; charset=utf-8');
 if(!/^[0-9a-f-]{36}$/i.test(id)){response.setHeader('X-Robots-Tag','noindex,nofollow');return response.status(400).send('잘못된 주소입니다.')}
 try{
  const [row]=await supabaseRows('pyeongjae_entries',`select=*&id=eq.${encodeURIComponent(id)}&status=eq.published&limit=1`);
  if(!row){response.setHeader('X-Robots-Tag','noindex,nofollow');return response.status(404).send('<!doctype html><meta charset="utf-8"><title>자료 없음</title><p>공개되지 않았거나 존재하지 않는 자료입니다.</p>')}
  const all=(await supabaseRows('pyeongjae_entries','select=id,book_no,sheet_no,side,status&status=eq.published&order=book_no.asc,sheet_no.asc')).sort((a,b)=>(a.book_no-b.book_no)||(a.sheet_no-b.sheet_no)||((a.side==='back'?2:1)-(b.side==='back'?2:1)));
  const pos=all.findIndex(x=>x.id===row.id),prev=all[pos-1],next=all[pos+1],canonical=`${SITE_URL}/pyeongjae-entry?id=${encodeURIComponent(row.id)}`,displayTitle=row.title;
  const description=clean(row.summary||`${row.title} — 원문·음독·직역·의역·참고.`).slice(0,170),tags=[...(row.people||[]),...(row.places||[]),...(row.tags||[])],keywords=['평재문집',`제${row.book_no}책`,`제${row.sheet_no}장`,faceLabel(row.side),row.genre,...(row.volume_no?[`권${row.volume_no}`]:[]),...tags];
  const allPages=Array.isArray(row.pages)?row.pages:[],matched=allPages.filter(p=>p.side===row.side),pages=matched.length?matched:allPages.slice(0,1);
  const schema={'@context':'https://schema.org','@type':'ScholarlyArticle',headline:displayTitle,description,url:canonical,mainEntityOfPage:canonical,inLanguage:['ko','zh-Hant'],datePublished:row.published_at||row.created_at,dateModified:row.updated_at,keywords,author:{'@type':'Person',name:'권태직'},publisher:{'@type':'Organization',name:'언어와 뇌 | 권우진 연구실'}};
  const nav=`<nav class="reader-nav">${prev?`<a href="/pyeongjae-entry?id=${prev.id}">← 이전 자료</a>`:'<span></span>'}<a href="/pyeongjae">전체 목록</a>${next?`<a href="/pyeongjae-entry?id=${next.id}">다음 자료 →</a>`:'<span></span>'}</nav>`;
  const refs=(Array.isArray(row.reference_links)?row.reference_links:[]).map(ref=>{const url=safeUrl(ref?.url);return url?`<li><a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(ref.label||url)}</a></li>`:''}).join('');
  const review=row.review_status==='검토 완료'?'':`<p class="review-note">이 자료는 원문 판독과 번역을 계속 검토하고 있습니다. 불확실한 글자와 인명·지명은 확인되는 대로 보완합니다.</p>`;
  const meta=`${row.volume_no?`권${row.volume_no} · `:''}${escapeHtml(row.genre)} · 조회 ${Number(row.view_count||0).toLocaleString()}`;
  const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(displayTitle)} | 『평재문집』</title><meta name="description" content="${escapeHtml(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${escapeHtml(canonical)}"><meta property="og:type" content="article"><meta property="og:title" content="${escapeHtml(displayTitle)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${escapeHtml(canonical)}">${keywords.map(k=>`<meta property="article:tag" content="${escapeHtml(k)}">`).join('')}<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><link rel="stylesheet" href="/pyeongjae/pyeongjae.css?v=face-mobile-20260828-2"></head><body><header class="site-header"><a href="/">언어와 뇌</a><nav><a href="/pyeongjae">평재문집 목록</a><a href="/">홈</a></nav></header><main class="reader"><header class="reader-head"><p class="reader-kicker">${meta}</p><h1>${escapeHtml(displayTitle)}</h1><div class="reader-meta"><span>최근 수정 ${new Date(row.updated_at).toLocaleDateString('ko-KR')}</span></div><div class="reader-tags">${tags.map(t=>`<a href="/pyeongjae?q=${encodeURIComponent(t)}">#${escapeHtml(t)}</a>`).join('')}</div>${review}</header>${nav}${pages.map(p=>pageMarkup(p,row)).join('')}${refs?`<section class="text-part"><h3>관련 문헌과 링크</h3><ul>${refs}</ul></section>`:''}<div class="correction"><a href="/?inquiry=question#about">정정·제보하기</a><button class="share" type="button">공유하기</button></div>${nav}</main><script src="/api/config"></script><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js"></script><script>const c=window.LANGUAGE_BRAIN_CONFIG;if(c?.supabaseUrl&&c?.supabasePublishableKey){const d=supabase.createClient(c.supabaseUrl,c.supabasePublishableKey);let v=localStorage.getItem('pj-viewer');if(!v){v=crypto.randomUUID();localStorage.setItem('pj-viewer',v)}d.rpc('increment_pyeongjae_view',{p_entry_id:'${row.id}',p_viewer:v})}document.querySelector('.share').onclick=async()=>{const x={title:document.title,url:location.href};if(navigator.share)try{await navigator.share(x)}catch(e){}else try{await navigator.clipboard.writeText(location.href);alert('링크가 복사되었습니다')}catch(e){prompt('주소를 복사하세요',location.href)}}</script></body></html>`;
  response.setHeader('Cache-Control','public,max-age=0,s-maxage=300,stale-while-revalidate=3600');return response.status(200).send(html)
 }catch(e){response.setHeader('X-Robots-Tag','noindex,nofollow');return response.status(503).send('<!doctype html><meta charset="utf-8"><title>자료를 불러올 수 없습니다</title><p>잠시 후 다시 시도해 주세요.</p>')}
}
